export const MOCK_STATIONS = [
  { id: '001', name: 'Hàm Nghi', address: '10 Hàm Nghi - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '002', name: 'Trường Cao đẳng Kỹ thuật Cao Thắng', address: '126 Hàm Nghi - Phường Nguyễn Thái Bình - Quận 1 - TP Hồ Chí Minh' },
  { id: '003', name: 'Công ty Cổ phần Vận tải Đường sắt Sài Gòn', address: '136 Hàm Nghi - Phường Bến Thành - Quận 1 - TP Hồ Chí Minh' },
  { id: '004', name: 'Thương xá Tax', address: '102 Nguyễn Huệ - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '005', name: 'Nguyễn Huệ', address: '1 Nguyễn Huệ - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '006', name: 'Sở Giao dịch Chứng khoán', address: '130-166 Nguyễn Công Trứ - Phường Nguyễn Thái Bình - Quận 1 - TP Hồ Chí Minh' },
  { id: '007', name: 'Phạm Hồng Thái', address: '46 Phạm Hồng Thái - Phường Bến Thành - Quận 1 - TP Hồ Chí Minh' },
  { id: '008', name: 'Công viên 23/9 (đường Phạm Ngũ Lão)', address: '111-103 Phạm Ngũ Lão - Phường Phạm Ngũ Lão - Quận 1 - TP Hồ Chí Minh' },
  { id: '009', name: 'Công viên 23/9 (đường Phạm Ngũ Lão)', address: 'Đối diện 201 Phạm Ngũ Lão - Quận 1 - TP Hồ Chí Minh' },
  { id: '010', name: 'Tòa nhà Kumho', address: '39 Lê Duẩn - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '011', name: 'Công viên 30/4', address: 'Công viên 30/4 - Lê Duẩn - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '012', name: 'Thảo Cầm Viên', address: '2 Nguyễn Bỉnh Khiêm - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '013', name: 'Sở Y Tế', address: '59 Nguyễn Thị Minh Khai - Phường Bến Thành - Quận 1 - TP Hồ Chí Minh' },
  { id: '014', name: 'Công viên Tao Đàn', address: 'Công viên Tao Đàn - Trương Định - Phường Bến Thành - Quận 1 - TP Hồ Chí Minh' },
  { id: '015', name: 'Cung Văn hóa Lao Động', address: '57 Nguyễn Thị Minh Khai - Phường Bến Thành - Quận 1 - TP Hồ Chí Minh' },
  { id: '016', name: 'Tổng công ty xây dựng Số 1', address: '111a Pasteur, Phường Bến Nghé, Quận 1, TP Hồ Chí Minh' },
  { id: '017', name: 'Nhà văn hóa Thanh Niên', address: '4 Phạm Ngọc Thạch - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '018', name: 'Mạc Đĩnh Chi', address: '22 Nguyễn Thị Minh Khai - Phường Đa Kao - Quận 1 - TP Hồ Chí Minh' },
  { id: '019', name: 'Trung tâm TDTT Hoa Lư', address: '2 Đinh Tiên Hoàng - Phường Đa Kao - Quận 1 - TP Hồ Chí Minh' },
  { id: '020', name: 'Công xã Paris', address: '1 Công xã Paris - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '021', name: 'Khách sạn Le Méridien Saigon', address: '3c Tôn Đức Thắng - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '022', name: 'Trung tâm thương mại Sài Gòn', address: '37 Đường Tôn Đức Thắng - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '023', name: 'Bảo tàng Tôn Đức Thắng', address: '5 Tôn Đức Thắng - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '024', name: 'Lê Thánh Tôn', address: '2 Lê Thánh Tôn - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '025', name: 'Sở Kế hoạch Đầu tư', address: '32 Lê Thánh Tôn - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '026', name: 'Công viên Chi Lăng', address: 'Lê Thánh Tôn - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '027', name: 'Bảo tàng Hồ Chí Minh', address: '65 Lý Tự Trọng - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '028', name: 'Công Trường Lam Sơn', address: '15 Công Trường Lam Sơn - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '029', name: 'Trường Mầm Non Bé Ngoan', address: '108 Nguyễn Đình Chiểu - Phường Đa Kao - Quận 1 - TP Hồ Chí Minh' },
  { id: '030', name: 'Khách Sạn Park Hyatt Sài Gòn', address: '15 Hai Bà Trưng - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '032', name: 'Trung tâm thương mại Saigon Centre', address: '65 Lê Lợi - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '033', name: 'Bệnh viện đa khoa Sài Gòn', address: '123 Lê Lợi - Phường Bến Thành - Quận 1 - TP Hồ Chí Minh' },
  { id: '034', name: 'Trường Tiểu Học Trần Hưng Đạo', address: '250 Đường Trần Hưng Đạo - Phường Nguyễn Cư Trinh - Quận 1 - TP Hồ Chí Minh' },
  { id: '035', name: 'Trống Đồng', address: '12b Cách Mạng Tháng 8 - Phường Bến Thành - Quận 1 - TP Hồ Chí Minh' },
  { id: '036', name: 'Huyền Trân Công Chúa', address: '1 Huyền Trân Công Chúa - Phường Bến Thành - Quận 1 - TP Hồ Chí Minh' },
  { id: '037', name: 'Bệnh viện Nhi Đồng 2', address: '33 Nguyễn Du - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '038', name: 'Chu Mạnh Trinh', address: '31 Nguyễn Du - Phường Bến Nghé - Quận 1 - TP Hồ Chí Minh' },
  { id: '039', name: 'Công viên Lê Văn Tám', address: 'Đối diện 227 Điện Biên Phủ - Phường Đa Kao - Quận 1 - TP Hồ Chí Minh' },
  { id: '040', name: 'Lê Lai', address: '60 Lê Lai - Phường Phạm Ngũ Lão - Quận 1 - TP Hồ Chí Minh' },
  { id: '041', name: 'Công viên 23/9 (đường Lê Lai)', address: 'Đối diện 144-146 Lê Lai - Phường Bến Thành - Quận 1 - TP Hồ Chí Minh' },
  { id: '042', name: 'Công viên 23/9 (đường Phạm Ngũ Lão)', address: 'Đối diện 311 Phạm Ngũ Lão - Phường Phạm Ngũ Lão - Quận 1 - TP Hồ Chí Minh' },
  { id: '044', name: 'Trạm Văn Phòng VNGo HCM', address: 'Số 7 Đường số 6, KDC Sông Giồng, Phường Bình Trưng, TPHCM' },
  { id: '045', name: 'Khánh sạn Wink', address: '75 Nguyễn Bỉnh Khiêm - Phường Đa Kao - Quận 1 - TP Hồ Chí Minh' },
  { id: '046', name: 'TINI Coworking', address: '152 Đ. Võ Văn Kiệt Phường Nguyễn Thái Bình Quận 1' },
  { id: '047', name: 'Nguyễn Siêu', address: '18 Nguyễn Siêu, phường Bến Nghé, Quận 1, TP Hồ Chí Minh' },
  { id: '048', name: 'Trạm Ga Metro Bến Thành (Đường Lê Lai)', address: '20 Lê Lai, Phường Bến Thành, Quận 1, TP Hồ Chí Minh' },
  { id: '049', name: 'Trạm Ga Metro Bến Thành (Đường Trần Hưng Đạo)', address: 'Đang Cập Nhật' },
  { id: '050', name: 'Metro Văn Thánh', address: 'Đang cập nhật' },
  { id: '051', name: 'Ga Tân Cảng', address: '687 Điện Biên Phủ, P25, Bình Thạnh, Hồ Chí Minh' },
  { id: '052', name: 'Trạm Khách Sạn NIKKO SAIGON', address: '235 Nguyễn Văn Cừ, phường Cầu Ông Lãnh, TP. HCM' },
  { id: '053', name: 'Trạm Nguyên Cơ Thạch', address: 'Góc ngã tư Mai Chí Thọ - Nguyễn Cơ Thạch' },
  { id: '054', name: 'Trạm Trần Quý Kiên', address: 'Góc ngã tư Mai Chí Thọ - Trần Quý Kiên' },
  { id: '055', name: 'Trạm Đường D1', address: 'Góc ngã tư Mai Chí Thọ - Đường D1' },
  { id: '056', name: 'Trạm New City', address: 'QPJP+35F Thủ Đức, Thành phố Hồ Chí Minh' },
];
